### ISSUE TITLE
remaps behaving weirdly with key combinations

### ISSUE THREAD

**Issue by robalb** [giladreich/QuickCut#19]
I have the following remap
`[bloc maius] ~ [esc]`
When i press `capslock`, the remap works as expected: `esc` is pressed instead of `capslock`

However, pressing the combination of any key + `capslock`, will trigger the real capslock.

This doesn't happen all the times, only after capslock has been pressed alone.
For example, if i type in sequence these keys:
capslock  ->  esc is pressed
a+capslock -> a is pressed, capslock toggles
a+capslock -> a is pressed (capslock doesnt toggle anymore)

**Comment by giladreich** [comment]
Hi @robalb,

Thank you very much for reporting!

Your key combination is quite interesting, but not very common. The only problem with your combination is that `A` key is not a [Modifier Key](https://en.wikipedia.org/wiki/Modifier_key) (MK) used within a shortcut:
```cpp
void QuickCutConsoleWindows::sendInput:
        switch (key.getKeyCode())
        {
            case VK_LEFT:
            case VK_UP:
            case VK_RIGHT:
            case VK_DOWN:
            case VK_RCONTROL:
            case VK_RMENU:
            case VK_LWIN:
            case VK_RWIN:
            case VK_APPS:
            case VK_PRIOR:
            case VK_NEXT:
            case VK_END:
            case VK_HOME:
            case VK_INSERT:
            case VK_DELETE:
            case VK_DIVIDE:
            case VK_NUMLOCK:
                input.ki.dwFlags |= KF_EXTENDED;
                break;
        }
```
hence it's printed out. If you use that key within a Key Shortcut (mapping multiple keys to key/s), we still need to let the operation system process the key as a regular key, since we can't determine whether the user was actually wanting to use `A` key for mapping or regular typing. Only in a scenario where it's a single Key mapped to a Key, we know for a fact that we can block this specific key before it's being processed to simulate the key mapping. That's one of the main reasons why the operation system does not support mapping shortcuts.
Another scenario to explain above, imagine I do this kind of mapping:
`A` + `B` + `C` to `ESC`, we shouldn't swallow these keys, because if the user was actually wanting to type `aba` and not `abc`, if we swallow these keys the user won't be even able to even type.

That being said, if I map a none MK + MK to some key, e.g.:
`A` + `CAPS-LOCK` = `A` will be outputted and `CAPS-LOCK` will be swollen/ignored (since it was the last key down press), but if it were the other way around, `CAPS-LOCK` + `A` will result in `A` not being printed:
```cpp
void QuickCutConsole::onKeysDown:
        QString srcKeyCodes = action->getSrcKeysCode();
        if (downKeyCodes == srcKeyCodes) // We have a match
        {
            Action::ActionType actionType = action->getType();
            if (actionType == Action::ActionKeyMap)
            {
                qDebug() << "Mapped keys -> " << qPrintable(downKeyCodes) << " ~ "
                         << qPrintable(action->getDstKeysCode());

                *outSwallowKey = true;
                // Send KeyUp to the current pressed keys before manipulating the fake keys.
                sendInput(action->getSrcKeys(), KeyboardHook::KeyUp);
                if (action->getDstKeys().count() > 1)
                    sendInput(action->getDstKeys(), KeyboardHook::KeyPress);
                else
                    sendInput(action->getDstKeys(), KeyboardHook::KeyDown);
            }
....
```
As you can see from this snippet, with a single key mapping (Key ~ Key), we can still swallow the event triggered, because we know that this specific key equals another key, hence we send `KeyDown` event. That's why for multiple keys combinations we send a `KeyPress` event, because if we have a shortcut key match, we let the operation system release the keys like as the user stopped holding the keys (since they were already processed by QuickCut).

I remember when I was initially implementing this, I was thinking about adding a Check-Box for letting users decide whether to swallow all keys specified for the shortcut (which is not very common) in the Action creation window. So if it's checked and you do this mapping for example `A` + `B` + `C` to `ESC` will result in A, B, C  keys to be disabled, so even if the user just pressed A it will be blocked. This is not a very common thing to do, hence if someone will bring good reasoning for this, I'll be ok to add this as a future feature.
